/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class Library extends javax.swing.JFrame {
    
    Library Library;
    DefaultTableModel model;

    /**
     * Creates new form Library
     */
    public Library() {
        initComponents();
        model = (DefaultTableModel) librarytable.getModel();
        LoadData();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        Text = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        book = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        BTY = new javax.swing.JTextField();
        DR = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        librarytable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        BT = new javax.swing.JTextField();
        DB = new javax.swing.JTextField();
        SI = new javax.swing.JTextField();
        SI1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        jLabel1.setText("LIBRARY");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("FIND:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 41, 40, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Book Title", "Book Type", "Date of Borrow", "Date of Return", "Student's ID", "Book's ID", " " }));
        combo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel2.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        Text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Text.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActionPerformed(evt);
            }
        });
        jPanel2.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 140, 20));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton4.setText("CLOSE");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 50, -1));

        book.setBackground(new java.awt.Color(204, 204, 204));
        book.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        book.setText("Books");
        book.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel2.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 50, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel7.setText("SELECT BOOKS YOU WANT TO BORROW:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        jButton6.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton6.setText("RESET");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 50, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1001, 97));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 109, 70, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 109, -1, -1));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 153, -1, -1));

        BTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTYActionPerformed(evt);
            }
        });
        jPanel1.add(BTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 149, 108, -1));
        jPanel1.add(DR, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 109, 120, -1));

        librarytable.setBackground(new java.awt.Color(204, 204, 204));
        librarytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Book's Title", "Book's Type", "Date of Borrow", "Date of Return", "Student's ID", "Book's ID"
            }
        ));
        librarytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarytableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                librarytableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(librarytable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 213, 1001, 191));

        jButton1.setText("Save");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 110, -1, -1));

        jButton2.setText("Update");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 135, -1, -1));

        jButton3.setText("Delete");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 161, -1, -1));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 119, -1, -1));

        BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActionPerformed(evt);
            }
        });
        jPanel1.add(BT, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 109, 108, -1));

        DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBActionPerformed(evt);
            }
        });
        jPanel1.add(DB, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 153, 120, -1));

        SI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIActionPerformed(evt);
            }
        });
        jPanel1.add(SI, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 153, 120, -1));

        SI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SI1ActionPerformed(evt);
            }
        });
        jPanel1.add(SI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 109, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Book's Title:");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 110, 75, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Book's Type:");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Date of Borrow:");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 154, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Date of Return:");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Book's ID:");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 110, 96, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("Select Student:");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 154, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActionPerformed
        try {
            DB_connection.init();
            PreparedStatement ps = null;
            Connection c = DB_connection.getConnection();
            ResultSet rs;
            
            if (combo.getSelectedItem().equals("ID")) {
                ps = c.prepareStatement("SELECT * FROM my.library WHERE ID LIKE '%" + Text.getText() + "%'");
            } else if (combo.getSelectedItem().equals("Book Title")) {
                ps = c.prepareStatement("SELECT * FROM my.library WHERE Book_title LIKE '%" + Text.getText() + "%'");
            } else if (combo.getSelectedItem().equals("Book Type")) {
                ps = c.prepareStatement("SELECT * FROM my.library WHERE Book_type LIKE '%" + Text.getText() + "%'");
            } else if (combo.getSelectedItem().equals("Date of Borrow")) {
                ps = c.prepareStatement("SELECT * FROM my.library WHERE Date_borrow LIKE '%" + Text.getText() + "%'");
            } else if (combo.getSelectedItem().equals("Date of Return")) {
                ps = c.prepareStatement("SELECT * FROM my.library WHERE Date_return LIKE '%" + Text.getText() + "%'");
            } else if (combo.getSelectedItem().equals("Student's ID")) {
                ps = c.prepareStatement("SELECT * FROM my.library WHERE STUDENTS_ID LIKE '%" + Text.getText() + "%'");
            } else if (combo.getSelectedItem().equals("Book's ID")) {
                ps = c.prepareStatement("SELECT * FROM my.library WHERE Book_ID LIKE '%" + Text.getText() + "%'");
            } else {
                JOptionPane.showMessageDialog(this, "Please select a valid search criteria.");
                return;
            }
            
            rs = ps.executeQuery();
            model.setRowCount(0);
            
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("ID"), rs.getString("Book_title"), rs.getString("Book_type"),
                    rs.getString("Date_borrow"), rs.getString("Date_return"), rs.getString("STUDENTS_ID"), rs.getString("Book_ID")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataEncode.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DB_connection.init();
            PreparedStatement ps;
            Connection c = DB_connection.getConnection();
            ResultSet rs;
            
            ps = c.prepareStatement("Insert into my.library (Book_title, Book_type, Date_borrow, Date_return, STUDENTS_ID, Book_ID ) "
                    + "values ('" + BT.getText() + "','" + BTY.getText() + "','" + DB.getText() + "','" + DR.getText() + "','" + SI.getText() + "','" + SI1.getText() + "')");
            
            if (!ps.execute()) {
                JOptionPane.showMessageDialog(this, "SUCCESSFULLY SAVE!!");
                LoadData();
                
                BT.setText("");
                BTY.setText("");
                DB.setText("");
                DR.setText("");
                SI.setText("");
                SI1.setText("");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataEncode.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void librarytableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarytableMouseClicked
        int row = librarytable.getSelectedRow();
        String ID = model.getValueAt(row, 0).toString();
        String Bt = model.getValueAt(row, 1).toString();
        String Bty = model.getValueAt(row, 2).toString();
        String Db = model.getValueAt(row, 3).toString();
        String Dr = model.getValueAt(row, 4).toString();
        String Si = model.getValueAt(row, 5).toString();
        String Si1 = model.getValueAt(row, 6).toString();
        
        BT.setText(Bt);
        BTY.setText(Bty);
        DB.setText(Db);
        DR.setText(Dr);
        SI.setText(Si);
        SI1.setText(Si1);
        

    }//GEN-LAST:event_librarytableMouseClicked

    private void librarytableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarytableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_librarytableMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = librarytable.getSelectedRow();
        String ID = model.getValueAt(row, 0).toString();
        
        try {
            DB_connection.init();
            PreparedStatement ps;
            Connection c = DB_connection.getConnection();
            ResultSet rs;
            ps = c.prepareStatement("DELETE FROM my.library WHERE ID = " + ID + " ");
            
            if (!ps.execute()) {
                JOptionPane.showMessageDialog(this, "SUCCESSFULLY DELETE!!");
                LoadData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataEncodeCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = librarytable.getSelectedRow();
        String ID = model.getValueAt(row, 0).toString();
        
        try {
            DB_connection.init();
            PreparedStatement ps;
            Connection c = DB_connection.getConnection();
            ResultSet rs;
            ps = c.prepareStatement("UPDATE my.library SET Book_title = ('" + BT.getText() + "'),"
                    + "Book_type = ('" + BTY.getText() + "'), Date_borrow = ('" + DB.getText() + "'),"
                    + " Date_return = ('" + DR.getText() + "'), STUDENTS_ID = ('" + SI.getText() + "'), Book_ID = ('" + SI1.getText() + "') WHERE ID = '" + ID + "' ");
            
            if (!ps.execute()) {
                JOptionPane.showMessageDialog(this, "SUCCESSFULLY UPDATED!!");
                LoadData();
                
                BT.setText("");
                BTY.setText("");
                DB.setText("");
                DR.setText("");
                SI.setText("");
                SI1.setText("");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataEncodeCourse.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTActionPerformed
 
    private void DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DBActionPerformed

    private void SIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIActionPerformed

    private void BTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTYActionPerformed

    private void SI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SI1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    listofstudents listofstudents;
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (listofstudents == null) {
            listofstudents = new listofstudents();
            listofstudents.Library = this;
        }        
        listofstudents.setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed
          MyLibrary Mylibary;
    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
         if (Mylibary == null) {
            Mylibary = new MyLibrary();
            Mylibary.Library = this;
        }        
        Mylibary.setVisible(true);
    }//GEN-LAST:event_bookActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                BT.setText("");
                BTY.setText("");
                DB.setText("");
                DR.setText("");
                SI.setText("");
                SI1.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed
    
    public void updateData(String data) {
        SI.setText(data);
    }
    
    public void updateData2 (String data, String data2, String data3) {
        SI1.setText(data);
        BTY.setText(data2);
        BT.setText(data3);
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library().setVisible(true);
            }
        });
    }
    
    void LoadData() {
        try {
            DB_connection.init();
            PreparedStatement ps;
            Connection c = DB_connection.getConnection();
            ResultSet rs;
            model.setRowCount(0);
            ps = c.prepareStatement("SELECT * FROM my.library;");
            rs = ps.executeQuery();
            
            while (rs.next()) {
                
                model.addRow(new Object[]{rs.getString("ID"), rs.getString("Book_title"), rs.getString("Book_type"),
                    rs.getString("Date_borrow"), rs.getString("Date_return"), rs.getString("STUDENTS_ID"), rs.getString("Book_ID")});
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(DataEncodeCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BT;
    private javax.swing.JTextField BTY;
    private javax.swing.JTextField DB;
    private javax.swing.JTextField DR;
    private javax.swing.JTextField SI;
    private javax.swing.JTextField SI1;
    private javax.swing.JTextField Text;
    private javax.swing.JButton book;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable librarytable;
    // End of variables declaration//GEN-END:variables

    void updateData2(String id) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
